"""مدل‌های SQLAlchemy. همه اینجا وارد می‌شوند تا Alembic آن‌ها را ببیند."""

from silp.db.base import Base
from silp.models.access import MaterialAccessEvent, Subscription, SubscriptionPlan
from silp.models.admin import AuditLog
from silp.models.content import ContentItem
from silp.models.delivery import (
    Certificate,
    Deliverable,
    DeliverableFile,
    Milestone,
    OpeningApplication,
    PeerEvaluation,
    ProjectActivity,
    ProjectArtifactVersion,
    ProjectMessage,
    ProjectReflection,
    ProjectTask,
    TeamOpening,
)
from silp.models.education import (
    Announcement,
    AttendanceRecord,
    ClassSession,
    Course,
    CourseMaterial,
    CourseOffering,
    CourseWeek,
    Enrollment,
    Resource,
    ResourceProgress,
    Term,
    WeekMaterial,
)
from silp.models.file import File
from silp.models.gamification import Badge, PointEntry, PointRule, UserBadge
from silp.models.idea import Idea, IdeaComment, IdeaVote
from silp.models.intake import IntakeRequest
from silp.models.identity import (
    NULL_SCOPE,
    OTPChallenge,
    RefreshToken,
    Role,
    User,
    UserRole,
)
from silp.models.messaging import (
    MessageTemplate,
    Notification,
    NotificationPreference,
    OutboxMessage,
    PushSubscription,
    UserChannel,
)
from silp.models.profile import (
    Profile,
    ProfileAsset,
    ProfileInterest,
    ProfileSkill,
    ProfileSurveyVersion,
)
from silp.models.project import (
    Project,
    ProjectApplication,
    ProjectInterest,
    ProjectRequiredAsset,
    ProjectRequiredSkill,
    ProjectRole,
    RecommendationFeedback,
    Team,
    TeamInvitation,
    TeamMember,
)
from silp.models.qa import QaReply, QaReplyVote, QaThread
from silp.models.quiz import (
    GradeAppeal,
    QuestionBankItem,
    Quiz,
    QuizAnswer,
    QuizAttempt,
    QuizQuestion,
)
from silp.models.research import (
    ResearchOutput,
    ResearchSubmission,
    ResearchSubmissionFile,
    ResearchTopic,
    ResearchTrack,
)
from silp.models.taxonomy import Asset, Interest, Skill, University
from silp.models.venture import Venture, VentureMetric, VentureStageChange

__all__ = [
    "AuditLog",
    "NULL_SCOPE",
    "Announcement",
    "Asset",
    "Badge",
    "AttendanceRecord",
    "Base",
    "Certificate",
    "ClassSession",
    "ContentItem",
    "Course",
    "CourseMaterial",
    "CourseOffering",
    "CourseWeek",
    "Deliverable",
    "DeliverableFile",
    "Enrollment",
    "File",
    "GradeAppeal",
    "Idea",
    "IdeaComment",
    "IdeaVote",
    "IntakeRequest",
    "Interest",
    "MaterialAccessEvent",
    "MessageTemplate",
    "Milestone",
    "Notification",
    "NotificationPreference",
    "OTPChallenge",
    "OpeningApplication",
    "OutboxMessage",
    "PeerEvaluation",
    "PointEntry",
    "PointRule",
    "Profile",
    "ProfileAsset",
    "ProfileInterest",
    "ProfileSkill",
    "ProfileSurveyVersion",
    "Project",
    "ProjectActivity",
    "ProjectApplication",
    "ProjectArtifactVersion",
    "ProjectInterest",
    "ProjectMessage",
    "ProjectReflection",
    "ProjectRequiredAsset",
    "ProjectRequiredSkill",
    "ProjectRole",
    "ProjectTask",
    "QaReply",
    "QaReplyVote",
    "QaThread",
    "QuestionBankItem",
    "Quiz",
    "QuizAnswer",
    "QuizAttempt",
    "QuizQuestion",
    "RecommendationFeedback",
    "RefreshToken",
    "ResearchOutput",
    "ResearchSubmission",
    "ResearchSubmissionFile",
    "ResearchTopic",
    "ResearchTrack",
    "Resource",
    "ResourceProgress",
    "Role",
    "Skill",
    "Subscription",
    "SubscriptionPlan",
    "Team",
    "TeamInvitation",
    "TeamMember",
    "TeamOpening",
    "Term",
    "University",
    "User",
    "UserBadge",
    "PushSubscription",
    "UserChannel",
    "UserRole",
    "Venture",
    "VentureMetric",
    "VentureStageChange",
    "WeekMaterial",
]
