"""مدل‌های SQLAlchemy. همه اینجا وارد می‌شوند تا Alembic آن‌ها را ببیند."""

from silp.db.base import Base
from silp.models.access import MaterialAccessEvent, Subscription, SubscriptionPlan
from silp.models.delivery import (
    Certificate,
    Deliverable,
    DeliverableFile,
    Milestone,
    PeerEvaluation,
    ProjectActivity,
    ProjectMessage,
    ProjectReflection,
    ProjectTask,
    TeamOpening,
)
from silp.models.education import (
    Announcement,
    AttendanceRecord,
    ClassSession,
    Course,
    CourseMaterial,
    CourseOffering,
    CourseWeek,
    Enrollment,
    Resource,
    ResourceProgress,
    Term,
    WeekMaterial,
)
from silp.models.file import File
from silp.models.gamification import Badge, PointEntry, PointRule, UserBadge
from silp.models.identity import (
    NULL_SCOPE,
    OTPChallenge,
    RefreshToken,
    Role,
    User,
    UserRole,
)
from silp.models.messaging import (
    MessageTemplate,
    Notification,
    NotificationPreference,
    OutboxMessage,
    UserChannel,
)
from silp.models.profile import (
    Profile,
    ProfileAsset,
    ProfileInterest,
    ProfileSkill,
    ProfileSurveyVersion,
)
from silp.models.project import (
    Project,
    ProjectApplication,
    ProjectInterest,
    ProjectRequiredAsset,
    ProjectRequiredSkill,
    ProjectRole,
    RecommendationFeedback,
    Team,
    TeamMember,
)
from silp.models.quiz import (
    GradeAppeal,
    QuestionBankItem,
    Quiz,
    QuizAnswer,
    QuizAttempt,
    QuizQuestion,
)
from silp.models.taxonomy import Asset, Interest, Skill, University

__all__ = [
    "NULL_SCOPE",
    "Announcement",
    "Asset",
    "Badge",
    "AttendanceRecord",
    "Base",
    "Certificate",
    "ClassSession",
    "Course",
    "CourseMaterial",
    "CourseOffering",
    "CourseWeek",
    "Deliverable",
    "DeliverableFile",
    "Enrollment",
    "File",
    "GradeAppeal",
    "Interest",
    "MaterialAccessEvent",
    "MessageTemplate",
    "Milestone",
    "Notification",
    "NotificationPreference",
    "OTPChallenge",
    "OutboxMessage",
    "PeerEvaluation",
    "PointEntry",
    "PointRule",
    "Profile",
    "ProfileAsset",
    "ProfileInterest",
    "ProfileSkill",
    "ProfileSurveyVersion",
    "Project",
    "ProjectActivity",
    "ProjectApplication",
    "ProjectInterest",
    "ProjectMessage",
    "ProjectReflection",
    "ProjectRequiredAsset",
    "ProjectRequiredSkill",
    "ProjectRole",
    "ProjectTask",
    "QuestionBankItem",
    "Quiz",
    "QuizAnswer",
    "QuizAttempt",
    "QuizQuestion",
    "RecommendationFeedback",
    "RefreshToken",
    "Resource",
    "ResourceProgress",
    "Role",
    "Skill",
    "Subscription",
    "SubscriptionPlan",
    "Team",
    "TeamMember",
    "TeamOpening",
    "Term",
    "University",
    "User",
    "UserBadge",
    "UserChannel",
    "UserRole",
    "WeekMaterial",
]
