/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ورود با رمز عبور
         * @description FR-AUTH-02 — پیام خطا هرگز افشا نمی‌کند که کاربر وجود دارد یا نه.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * خروج از نشست جاری
         * @description خروج بی‌اثر در تکرار است: خروج از نشستی که وجود ندارد هم ۲۰۴ می‌دهد.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * درخواست کد یک‌بارمصرف
         * @description FR-AUTH-01 — کد شش‌رقمی با اعتبار ۱۲۰ ثانیه.
         *
         *     کانال اگر تصریح نشده باشد از شکل ورودی حدس زده می‌شود، تا کاربر
         *     مجبور به انتخاب نباشد.
         */
        post: operations["request_otp_api_v1_auth_otp_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * تأیید کد و دریافت توکن
         * @description FR-AUTH-01 — در صورت نبود حساب، ساخته می‌شود و نقش STUDENT می‌گیرد.
         */
        post: operations["verify_otp_api_v1_auth_otp_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * تمدید توکن
         * @description FR-AUTH-03 — چرخش اجباری. توکن قدیمی بلافاصله باطل می‌شود.
         *
         *     استفادهٔ دوباره از یک توکن باطل‌شده ⇒ `401 TOKEN_REUSE_DETECTED` و
         *     ابطال کل خانواده.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * فهرست نشست‌های فعال
         * @description FR-AUTH-03 — کاربر باید بتواند دستگاه‌های واردشده را ببیند.
         */
        get: operations["list_sessions_api_v1_auth_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * قطع یک نشست
         * @description ۴۰۴ برای نشست کاربر دیگر — وجود آن نباید افشا شود (§6.4 قاعدهٔ ۴).
         */
        delete: operations["revoke_session_api_v1_auth_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * اطلاعات کاربر جاری
         * @description اطلاعات تماس پوشانده برمی‌گردد (NFR-01): `0912***4567`.
         */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * به‌روزرسانی اطلاعات پایه
         * @description `PATCH` جزئی — فیلدهای نفرستاده دست‌نخورده می‌مانند (§5.3).
         */
        patch: operations["update_profile_api_v1_me_profile_patch"];
        trace?: never;
    };
    "/api/v1/me/survey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** وضعیت کامل ارزیابی نیمرخ */
        get: operations["get_survey_api_v1_me_survey_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/survey/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** گام ۲ — امکانات */
        patch: operations["save_assets_api_v1_me_survey_assets_patch"];
        trace?: never;
    };
    "/api/v1/me/survey/interests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** گام ۳ — علاقه‌ها */
        patch: operations["save_interests_api_v1_me_survey_interests_patch"];
        trace?: never;
    };
    "/api/v1/me/survey/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** گام ۴ — ترجیحات */
        patch: operations["save_preferences_api_v1_me_survey_preferences_patch"];
        trace?: never;
    };
    "/api/v1/me/survey/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** گام ۱ — مهارت‌ها */
        patch: operations["save_skills_api_v1_me_survey_skills_patch"];
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * فهرست و جستجوی پروژه
         * @description فهرست پروژه‌های باز.
         *
         *     جستجو روی ستون تولیدشدهٔ `search_norm` با ایندکس trigram انجام می‌شود،
         *     نه `ILIKE '%…%'` — §4.11.
         */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/recommended": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * پیشنهادهای شخصی با دلیل
         * @description §5.7 — هر پیشنهاد با امتیاز، تفکیک شش‌گانه و دلایل فارسی.
         *
         *     متن دلیل از سرور می‌آید و مستقیماً نمایش داده می‌شود (§8.10).
         */
        get: operations["recommended_api_v1_projects_recommended_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * جزئیات پروژه + تطابق من
         * @description اگر کاربر وارد باشد، `match` هم محاسبه می‌شود.
         *
         *     این محاسبه از کش پیشنهادها نمی‌آید: کاربر ممکن است پروژه‌ای را ببیند
         *     که در ده تای برتر نبوده و همچنان حق دارد بداند چقدر به او می‌خورد.
         */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{project_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * بازخورد روی یک پیشنهاد
         * @description §8.9 — «به من نمی‌خورد» / «دیگر نشانم نده» / «فعلاً نه، ولی جالب است».
         *
         *     نظر تازه جای نظر قبلی را می‌گیرد؛ دانشجو باید بتواند نظرش را عوض کند.
         */
        post: operations["submit_feedback_api_v1_recommendations__project_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taxonomy/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** فهرست امکانات */
        get: operations["list_assets_api_v1_taxonomy_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taxonomy/interests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** فهرست حوزه‌های علاقه */
        get: operations["list_interests_api_v1_taxonomy_interests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taxonomy/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** فهرست مهارت‌ها */
        get: operations["list_skills_api_v1_taxonomy_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taxonomy/universities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * جستجوی دانشگاه
         * @description جستجو با `fa_normalize` انجام می‌شود، نه `ILIKE` خام.
         *
         *     کاربر «دانشگاه شهيد باهنر» با «ي» عربی می‌نویسد و باید همان نتیجه را
         *     بگیرد که با «ی» فارسی — §4.11.
         */
        get: operations["search_universities_api_v1_taxonomy_universities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssetOut */
        AssetOut: {
            /** Category */
            category: string;
            /** Code */
            code: string;
            /** Icon */
            icon?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sort Order */
            sort_order: number;
            /** Title Fa */
            title_fa: string;
        };
        /** AssetRequirementOut */
        AssetRequirementOut: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Is Mandatory */
            is_mandatory: boolean;
            /** Title Fa */
            title_fa: string;
        };
        /**
         * AssetsStepIn
         * @description گام ۲ جایگزینی کامل است: فهرست خالی یعنی «هیچ امکانی ندارم».
         */
        AssetsStepIn: {
            /** Asset Ids */
            asset_ids: string[];
        };
        /**
         * AuthUserOut
         * @description کاربر در پاسخ ورود — §5.2. اطلاعات تماس پوشانده می‌شود (NFR-01).
         */
        AuthUserOut: {
            /** Display Name */
            display_name?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Onboarding State
             * @enum {string}
             */
            onboarding_state: "BASIC_INFO_REQUIRED" | "SURVEY_REQUIRED" | "SURVEY_INCOMPLETE" | "COMPLETE";
            /** Roles */
            roles: string[];
            /** Username */
            username?: string | null;
        };
        /**
         * BreakdownOut
         * @description شش زیرامتیاز §8.2 تا §8.7، برای شفافیت امتیاز (اصل ۳ §00).
         */
        BreakdownOut: {
            /** Asset */
            asset: number;
            /** Goal */
            goal: number;
            /** Interest */
            interest: number;
            /** Skill */
            skill: number;
            /** Style */
            style: number;
            /** Time */
            time: number;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * ErrorResponse
         * @description قالب ثابت خطا — §5.1. فقط برای مستندسازی OpenAPI.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InterestAnswerIn */
        InterestAnswerIn: {
            /**
             * Interest Id
             * Format: uuid
             */
            interest_id: string;
            /** Level */
            level: number;
        };
        /** InterestListOut */
        InterestListOut: {
            /** Items */
            items: components["schemas"]["InterestOut"][];
            /** Level Labels */
            level_labels: components["schemas"]["LevelLabel"][];
        };
        /** InterestOut */
        InterestOut: {
            /** Code */
            code: string;
            /** Icon */
            icon?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sort Order */
            sort_order: number;
            /** Title Fa */
            title_fa: string;
        };
        /** InterestRefOut */
        InterestRefOut: {
            /**
             * Interest Id
             * Format: uuid
             */
            interest_id: string;
            /** Title Fa */
            title_fa: string;
        };
        /** InterestsStepIn */
        InterestsStepIn: {
            /** Interests */
            interests: components["schemas"]["InterestAnswerIn"][];
        };
        /**
         * LevelLabel
         * @description متن توصیفی هر سطح — FR-PROF-01.
         *
         *     سرور این متن‌ها را می‌فرستد تا `SkillSlider` آن‌ها را در خود ثابت
         *     نکند؛ تعریف سطح باید در فرم و در توضیح توصیه‌گر یکی باشد.
         */
        LevelLabel: {
            /** Label */
            label: string;
            /** Level */
            level: number;
        };
        /** LoginOut */
        LoginOut: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
            user: components["schemas"]["AuthUserOut"];
        };
        /** LogoutIn */
        LogoutIn: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** MatchOut */
        MatchOut: {
            breakdown: components["schemas"]["BreakdownOut"];
            /**
             * Is Stretch
             * @default false
             */
            is_stretch: boolean;
            /** Match Score */
            match_score: number;
            /** Reasons */
            reasons: components["schemas"]["ReasonOut"][];
        };
        /**
         * MeOut
         * @description §5.3 `GET /me` — نسخهٔ M1.
         *
         *     امتیاز (M5) و شمارندهٔ اعلان (M6) بعداً افزوده می‌شوند. آنچه هست، همان
         *     شکل نهایی را دارد تا کلاینت بعداً بازنویسی نشود.
         */
        MeOut: {
            /** Email */
            email?: string | null;
            /**
             * Email Verified
             * @default false
             */
            email_verified: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mobile */
            mobile?: string | null;
            /**
             * Mobile Verified
             * @default false
             */
            mobile_verified: boolean;
            onboarding: components["schemas"]["OnboardingOut"];
            profile?: components["schemas"]["ProfileOut"] | null;
            /** Roles */
            roles: components["schemas"]["RoleGrantOut"][];
            /** Username */
            username?: string | null;
        };
        /**
         * OTPRequestIn
         * @example {
         *       "channel": "SMS",
         *       "destination": "09121234567",
         *       "purpose": "LOGIN"
         *     }
         */
        OTPRequestIn: {
            /** Channel */
            channel?: ("SMS" | "EMAIL") | null;
            /** Destination */
            destination: string;
            /**
             * Purpose
             * @default LOGIN
             * @enum {string}
             */
            purpose: "LOGIN" | "VERIFY_EMAIL" | "VERIFY_MOBILE" | "RESET_PASSWORD";
        };
        /** OTPRequestOut */
        OTPRequestOut: {
            /** Challenge Id */
            challenge_id: string;
            /** Expires In */
            expires_in: number;
            /** Masked Destination */
            masked_destination: string;
            /** Resend After */
            resend_after: number;
        };
        /** OTPVerifyIn */
        OTPVerifyIn: {
            /**
             * Challenge Id
             * Format: uuid
             */
            challenge_id: string;
            /** Code */
            code: string;
        };
        /** OnboardingOut */
        OnboardingOut: {
            /** Completed Steps */
            completed_steps: number;
            /** Next Route */
            next_route: string;
            /**
             * State
             * @enum {string}
             */
            state: "BASIC_INFO_REQUIRED" | "SURVEY_REQUIRED" | "SURVEY_INCOMPLETE" | "COMPLETE";
            /** Total Steps */
            total_steps: number;
        };
        /** Page[ProjectSummaryOut] */
        Page_ProjectSummaryOut_: {
            /** Has Next */
            has_next: boolean;
            /** Items */
            items: components["schemas"]["ProjectSummaryOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * PasswordLoginIn
         * @description FR-AUTH-02 — موبایل یا ایمیل + رمز.
         */
        PasswordLoginIn: {
            /** Identifier */
            identifier: string;
            /** Password */
            password: string;
        };
        /** PreferencesStepIn */
        PreferencesStepIn: {
            /** Primary Goal */
            primary_goal?: ("GRADE" | "LEARNING" | "PUBLICATION" | "INCOME" | "STARTUP" | "EMPLOYMENT") | null;
            /** Weekly Hours */
            weekly_hours?: number | null;
            /** Work Style */
            work_style?: ("SOLO" | "TEAM" | "EITHER") | null;
        };
        /**
         * ProfileOut
         * @description نیمرخ در پاسخ `GET /me` — §5.3.
         *
         *     کد ملی هرگز اینجا نمی‌آید، حتی پوشانده (NFR-01). مسیر اختصاصی با
         *     مجوز `profile.view.national_id` دارد.
         */
        ProfileOut: {
            /** Avatar Url */
            avatar_url?: string | null;
            /** Bio */
            bio?: string | null;
            /** Degree Level */
            degree_level?: ("ASSOCIATE" | "BACHELOR" | "MASTER" | "PHD" | "OTHER") | null;
            /** Degree Level Fa */
            degree_level_fa?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Entry Year */
            entry_year?: number | null;
            /** Field Of Study */
            field_of_study?: string | null;
            /** First Name */
            first_name: string;
            /**
             * Is Public
             * @default false
             */
            is_public: boolean;
            /** Last Name */
            last_name: string;
            /** Primary Goal */
            primary_goal?: ("GRADE" | "LEARNING" | "PUBLICATION" | "INCOME" | "STARTUP" | "EMPLOYMENT") | null;
            university?: components["schemas"]["UniversityRef"] | null;
            /** Weekly Hours */
            weekly_hours?: number | null;
            /** Work Style */
            work_style?: ("SOLO" | "TEAM" | "EITHER") | null;
        };
        /**
         * ProfileUpdateIn
         * @description `PATCH /me/profile` — همهٔ فیلدها اختیاری‌اند.
         *
         *     `None` یعنی «تغییر نده». این قرارداد در §5.3 صریح است و باعث می‌شود
         *     فرم چندگامی بتواند فقط فیلدهای همان گام را بفرستد.
         */
        ProfileUpdateIn: {
            /** Bio */
            bio?: string | null;
            /** Birth Year */
            birth_year?: number | null;
            /** Degree Level */
            degree_level?: ("ASSOCIATE" | "BACHELOR" | "MASTER" | "PHD" | "OTHER") | null;
            /** Display Name */
            display_name?: string | null;
            /** Entry Year */
            entry_year?: number | null;
            /** Field Of Study */
            field_of_study?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Gender */
            gender?: ("M" | "F" | "UNDISCLOSED") | null;
            /** Last Name */
            last_name?: string | null;
            /** Student Number */
            student_number?: string | null;
            /** University Id */
            university_id?: string | null;
        };
        /** ProjectDetailOut */
        ProjectDetailOut: {
            /**
             * Active Members
             * @default 0
             */
            active_members: number;
            /** Applications Close At */
            applications_close_at?: string | null;
            /** Deadline On */
            deadline_on?: string | null;
            /** Description */
            description: string;
            /** Difficulty */
            difficulty: number;
            /** Difficulty Fa */
            difficulty_fa: string;
            /** Expected Output */
            expected_output: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Interests */
            interests?: components["schemas"]["InterestRefOut"][];
            /**
             * Kind
             * @enum {string}
             */
            kind: "A_VENTURE" | "B_RESEARCH" | "C_PROBLEM" | "D_PERSONAL";
            /** Kind Fa */
            kind_fa: string;
            match?: components["schemas"]["MatchOut"] | null;
            /**
             * Open Seats
             * @default 0
             */
            open_seats: number;
            /** Required Assets */
            required_assets?: components["schemas"]["AssetRequirementOut"][];
            /** Required Skills */
            required_skills?: components["schemas"]["SkillRequirementOut"][];
            /** Rewards */
            rewards?: {
                [key: string]: unknown;
            };
            /** Slug */
            slug: string;
            /**
             * Status
             * @enum {string}
             */
            status: "DRAFT" | "OPEN" | "IN_PROGRESS" | "PAUSED" | "COMPLETED" | "CANCELLED";
            /** Summary */
            summary: string;
            /** Tags */
            tags?: string[];
            /** Team Size Max */
            team_size_max: number;
            /** Team Size Min */
            team_size_min: number;
            /** Time Commitment Hpw */
            time_commitment_hpw?: number | null;
            /** Title Fa */
            title_fa: string;
            /**
             * Work Style
             * @enum {string}
             */
            work_style: "SOLO" | "TEAM" | "EITHER";
        };
        /**
         * ProjectSummaryOut
         * @description پروژه در فهرست‌ها و داخل کارت پیشنهاد — §5.7.
         */
        ProjectSummaryOut: {
            /**
             * Active Members
             * @default 0
             */
            active_members: number;
            /** Applications Close At */
            applications_close_at?: string | null;
            /** Deadline On */
            deadline_on?: string | null;
            /** Difficulty */
            difficulty: number;
            /** Difficulty Fa */
            difficulty_fa: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "A_VENTURE" | "B_RESEARCH" | "C_PROBLEM" | "D_PERSONAL";
            /** Kind Fa */
            kind_fa: string;
            /**
             * Open Seats
             * @default 0
             */
            open_seats: number;
            /** Slug */
            slug: string;
            /**
             * Status
             * @enum {string}
             */
            status: "DRAFT" | "OPEN" | "IN_PROGRESS" | "PAUSED" | "COMPLETED" | "CANCELLED";
            /** Summary */
            summary: string;
            /** Tags */
            tags?: string[];
            /** Team Size Max */
            team_size_max: number;
            /** Team Size Min */
            team_size_min: number;
            /** Time Commitment Hpw */
            time_commitment_hpw?: number | null;
            /** Title Fa */
            title_fa: string;
            /**
             * Work Style
             * @enum {string}
             */
            work_style: "SOLO" | "TEAM" | "EITHER";
        };
        /**
         * ReasonOut
         * @description دلیل آمادهٔ نمایش — §8.10. متن را بک‌اند می‌سازد، نه کلاینت.
         */
        ReasonOut: {
            /** Contribution */
            contribution: number;
            /**
             * Polarity
             * @enum {string}
             */
            polarity: "POSITIVE" | "WARNING";
            /** Text */
            text: string;
            /** Type */
            type: string;
        };
        /** RecommendationFeedbackIn */
        RecommendationFeedbackIn: {
            /** Reason */
            reason?: string | null;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "NOT_RELEVANT" | "INTERESTED" | "DISMISSED";
        };
        /**
         * RecommendationItemOut
         * @description یک پیشنهاد — §5.7 `GET /projects/recommended`.
         */
        RecommendationItemOut: {
            breakdown: components["schemas"]["BreakdownOut"];
            /**
             * Is Stretch
             * @default false
             */
            is_stretch: boolean;
            /** Match Score */
            match_score: number;
            project: components["schemas"]["ProjectSummaryOut"];
            /** Reasons */
            reasons: components["schemas"]["ReasonOut"][];
        };
        /** RecommendationsOut */
        RecommendationsOut: {
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Items */
            items: components["schemas"]["RecommendationItemOut"][];
            /** Profile Completeness */
            profile_completeness: number;
        };
        /** RefreshIn */
        RefreshIn: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RoleGrantOut */
        RoleGrantOut: {
            /** Code */
            code: string;
            /** Scope Id */
            scope_id?: string | null;
            /** Scope Type */
            scope_type: string;
        };
        /**
         * SessionOut
         * @description یک نشست فعال — §5.2 `GET /auth/sessions`.
         */
        SessionOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ip Address */
            ip_address: string | null;
            /** Is Current */
            is_current: boolean;
            /** User Agent */
            user_agent: string | null;
        };
        /** SkillAnswerIn */
        SkillAnswerIn: {
            /** Level */
            level: number;
            /**
             * Skill Id
             * Format: uuid
             */
            skill_id: string;
        };
        /** SkillListOut */
        SkillListOut: {
            /** Items */
            items: components["schemas"]["SkillOut"][];
            /** Level Labels */
            level_labels: components["schemas"]["LevelLabel"][];
        };
        /** SkillOut */
        SkillOut: {
            /** Category */
            category: string;
            /** Code */
            code: string;
            /** Icon */
            icon?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Core */
            is_core: boolean;
            /** Sort Order */
            sort_order: number;
            /** Title En */
            title_en: string;
            /** Title Fa */
            title_fa: string;
        };
        /** SkillRequirementOut */
        SkillRequirementOut: {
            /** Is Teachable */
            is_teachable: boolean;
            /** Min Level */
            min_level: number;
            /**
             * Skill Id
             * Format: uuid
             */
            skill_id: string;
            /** Title Fa */
            title_fa: string;
            /** Weight */
            weight: number;
        };
        /** SkillsStepIn */
        SkillsStepIn: {
            /** Skills */
            skills: components["schemas"]["SkillAnswerIn"][];
        };
        /** SurveyInterestOut */
        SurveyInterestOut: {
            /**
             * Interest Id
             * Format: uuid
             */
            interest_id: string;
            /** Level */
            level: number;
        };
        /**
         * SurveyOut
         * @description `GET /me/survey` — وضعیت کامل ارزیابی.
         */
        SurveyOut: {
            /** Asset Ids */
            asset_ids: string[];
            /** Completed Steps */
            completed_steps: number;
            /** Interests */
            interests: components["schemas"]["SurveyInterestOut"][];
            /** Primary Goal */
            primary_goal?: ("GRADE" | "LEARNING" | "PUBLICATION" | "INCOME" | "STARTUP" | "EMPLOYMENT") | null;
            /** Skills */
            skills: components["schemas"]["SurveySkillOut"][];
            /** Total Steps */
            total_steps: number;
            /** Weekly Hours */
            weekly_hours?: number | null;
            /** Work Style */
            work_style?: ("SOLO" | "TEAM" | "EITHER") | null;
        };
        /** SurveySkillOut */
        SurveySkillOut: {
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean;
            /** Level */
            level: number;
            /**
             * Skill Id
             * Format: uuid
             */
            skill_id: string;
        };
        /**
         * SurveyStepOut
         * @description پاسخ هر گام — §5.3.
         *
         *     `preview_recommendations` همان «لحظهٔ طلایی» §01 است: سرور بلافاصله
         *     پس از گام ۱ سه پیشنهاد برمی‌گرداند، حتی با نیمرخ ۲۵٪ کامل.
         */
        SurveyStepOut: {
            /** Completed Steps */
            completed_steps: number;
            /** Preview Recommendations */
            preview_recommendations?: components["schemas"]["RecommendationItemOut"][];
            /** Total Steps */
            total_steps: number;
        };
        /** TokenPairOut */
        TokenPairOut: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
        };
        /** UniversityOut */
        UniversityOut: {
            /** City */
            city?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Province */
            province?: string | null;
            /** Title En */
            title_en?: string | null;
            /** Title Fa */
            title_fa: string;
            /** Type */
            type?: string | null;
        };
        /** UniversityRef */
        UniversityRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title Fa */
            title_fa: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordLoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOut"];
                };
            };
            /** @description احراز هویت نشده */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description محدودیت نرخ */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description احراز هویت نشده */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description محدودیت نرخ */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    request_otp_api_v1_auth_otp_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OTPRequestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OTPRequestOut"];
                };
            };
            /** @description احراز هویت نشده */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description محدودیت نرخ */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    verify_otp_api_v1_auth_otp_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OTPVerifyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOut"];
                };
            };
            /** @description احراز هویت نشده */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description محدودیت نرخ */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairOut"];
                };
            };
            /** @description احراز هویت نشده */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description محدودیت نرخ */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_sessions_api_v1_auth_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
            /** @description احراز هویت نشده */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description محدودیت نرخ */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    revoke_session_api_v1_auth_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description احراز هویت نشده */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description محدودیت نرخ */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description احراز هویت نشده */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_profile_api_v1_me_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description احراز هویت نشده */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_survey_api_v1_me_survey_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyOut"];
                };
            };
            /** @description احراز هویت نشده */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    save_assets_api_v1_me_survey_assets_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetsStepIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyStepOut"];
                };
            };
            /** @description احراز هویت نشده */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_interests_api_v1_me_survey_interests_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterestsStepIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyStepOut"];
                };
            };
            /** @description احراز هویت نشده */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_preferences_api_v1_me_survey_preferences_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesStepIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyStepOut"];
                };
            };
            /** @description احراز هویت نشده */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_skills_api_v1_me_survey_skills_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillsStepIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyStepOut"];
                };
            };
            /** @description احراز هویت نشده */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                kind?: string | null;
                work_style?: string | null;
                difficulty_max?: number | null;
                skill_id?: string | null;
                interest_id?: string | null;
                /** @description جستجوی فارسی */
                q?: string | null;
                sort?: "match" | "newest" | "popular" | "deadline";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ProjectSummaryOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommended_api_v1_projects_recommended_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationsOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_api_v1_recommendations__project_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationFeedbackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assets_api_v1_taxonomy_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"][];
                };
            };
        };
    };
    list_interests_api_v1_taxonomy_interests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterestListOut"];
                };
            };
        };
    };
    list_skills_api_v1_taxonomy_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillListOut"];
                };
            };
        };
    };
    search_universities_api_v1_taxonomy_universities_get: {
        parameters: {
            query?: {
                /** @description بخشی از نام دانشگاه */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniversityOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
